# Generated by Django 2.1 on 2018-08-16 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlliplanMed',
            fields=[
                ('age_from', models.PositiveIntegerField()),
                ('age_to', models.PositiveIntegerField()),
                ('cov_10k', models.FloatField(blank=True, null=True)),
                ('cov_25k', models.FloatField(blank=True, null=True)),
                ('cov_50k', models.FloatField(blank=True, null=True)),
                ('cov_100k', models.FloatField(blank=True, null=True)),
                ('cov_150k', models.FloatField(blank=True, null=True)),
                ('plan_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'alliplan_med',
            },
        ),
        migrations.CreateModel(
            name='AlliplanNomed',
            fields=[
                ('age_from', models.PositiveIntegerField()),
                ('age_to', models.PositiveIntegerField()),
                ('cov_10k', models.FloatField(blank=True, null=True)),
                ('cov_25k', models.FloatField(blank=True, null=True)),
                ('cov_50k', models.FloatField(blank=True, null=True)),
                ('cov_100k', models.FloatField(blank=True, null=True)),
                ('cov_150k', models.FloatField(blank=True, null=True)),
                ('plan_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'alliplan_nomed',
            },
        ),
        migrations.CreateModel(
            name='BerkplanMed',
            fields=[
                ('age_from', models.PositiveIntegerField()),
                ('age_to', models.PositiveIntegerField()),
                ('cov_10k', models.FloatField(blank=True, null=True)),
                ('cov_15k', models.FloatField(blank=True, null=True)),
                ('cov_25k', models.FloatField(blank=True, null=True)),
                ('cov_50k', models.FloatField(blank=True, null=True)),
                ('cov_100k', models.FloatField(blank=True, null=True)),
                ('cov_150k', models.FloatField(blank=True, null=True)),
                ('plan_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'berkplan_med',
            },
        ),
        migrations.CreateModel(
            name='BerkplanNomed',
            fields=[
                ('age_from', models.PositiveIntegerField()),
                ('age_to', models.PositiveIntegerField()),
                ('cov_10k', models.FloatField(blank=True, null=True)),
                ('cov_15k', models.FloatField(blank=True, null=True)),
                ('cov_25k', models.FloatField(blank=True, null=True)),
                ('cov_50k', models.FloatField(blank=True, null=True)),
                ('cov_100k', models.FloatField(blank=True, null=True)),
                ('cov_150k', models.FloatField(blank=True, null=True)),
                ('plan_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'berkplan_nomed',
            },
        ),
        migrations.CreateModel(
            name='ManuplanMed',
            fields=[
                ('age_from', models.PositiveIntegerField()),
                ('age_to', models.PositiveIntegerField()),
                ('cov_15k', models.FloatField(blank=True, null=True)),
                ('cov_25k', models.FloatField(blank=True, null=True)),
                ('cov_50k', models.FloatField(blank=True, null=True)),
                ('cov_100k', models.FloatField(blank=True, null=True)),
                ('cov_150k', models.FloatField(blank=True, null=True)),
                ('plan_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'manuplan_med',
            },
        ),
        migrations.CreateModel(
            name='ManuplanNomed',
            fields=[
                ('age_from', models.PositiveIntegerField()),
                ('age_to', models.PositiveIntegerField()),
                ('cov_15k', models.FloatField(blank=True, null=True)),
                ('cov_25k', models.FloatField(blank=True, null=True)),
                ('cov_50k', models.FloatField(blank=True, null=True)),
                ('cov_100k', models.FloatField(blank=True, null=True)),
                ('cov_150k', models.FloatField(blank=True, null=True)),
                ('plan_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'manuplan_nomed',
            },
        ),
        migrations.CreateModel(
            name='TicplanMed',
            fields=[
                ('age_from', models.PositiveIntegerField()),
                ('age_to', models.PositiveIntegerField()),
                ('cov_10k', models.FloatField(blank=True, null=True)),
                ('cov_15k', models.FloatField(blank=True, null=True)),
                ('cov_25k', models.FloatField(blank=True, null=True)),
                ('cov_50k', models.FloatField(blank=True, null=True)),
                ('cov_100k', models.FloatField(blank=True, null=True)),
                ('cov_150k', models.FloatField(blank=True, null=True)),
                ('plan_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'ticplan_med',
            },
        ),
        migrations.CreateModel(
            name='TicplanNomed',
            fields=[
                ('age_from', models.PositiveIntegerField()),
                ('age_to', models.PositiveIntegerField()),
                ('cov_10k', models.FloatField(blank=True, null=True)),
                ('cov_15k', models.FloatField(blank=True, null=True)),
                ('cov_25k', models.FloatField(blank=True, null=True)),
                ('cov_50k', models.FloatField(blank=True, null=True)),
                ('cov_100k', models.FloatField(blank=True, null=True)),
                ('cov_150k', models.FloatField(blank=True, null=True)),
                ('plan_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'ticplan_nomed',
            },
        ),
    ]
