# Generated by Django 2.1 on 2018-09-01 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insprices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GMSplanMed',
            fields=[
                ('age_from', models.PositiveIntegerField()),
                ('age_to', models.PositiveIntegerField()),
                ('cov_25k', models.FloatField(blank=True, null=True)),
                ('cov_50k', models.FloatField(blank=True, null=True)),
                ('cov_100k', models.FloatField(blank=True, null=True)),
                ('cov_150k', models.FloatField(blank=True, null=True)),
                ('plan_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'gmsplan_med',
            },
        ),
        migrations.CreateModel(
            name='Tfirstplan_med',
            fields=[
                ('age_from', models.PositiveIntegerField()),
                ('age_to', models.PositiveIntegerField()),
                ('cov_10k', models.FloatField(blank=True, null=True)),
                ('cov_15k', models.FloatField(blank=True, null=True)),
                ('cov_25k', models.FloatField(blank=True, null=True)),
                ('cov_50k', models.FloatField(blank=True, null=True)),
                ('cov_100k', models.FloatField(blank=True, null=True)),
                ('cov_150k', models.FloatField(blank=True, null=True)),
                ('plan_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'tfirstplan_med',
            },
        ),
        migrations.CreateModel(
            name='Tfirstplan_nomed',
            fields=[
                ('age_from', models.PositiveIntegerField()),
                ('age_to', models.PositiveIntegerField()),
                ('cov_10k', models.FloatField(blank=True, null=True)),
                ('cov_15k', models.FloatField(blank=True, null=True)),
                ('cov_25k', models.FloatField(blank=True, null=True)),
                ('cov_50k', models.FloatField(blank=True, null=True)),
                ('cov_100k', models.FloatField(blank=True, null=True)),
                ('cov_150k', models.FloatField(blank=True, null=True)),
                ('plan_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'tfirstplan_nomed',
            },
        ),
        migrations.CreateModel(
            name='TugoplanMed',
            fields=[
                ('age_from', models.PositiveIntegerField()),
                ('age_to', models.PositiveIntegerField()),
                ('cov_10k', models.FloatField(blank=True, null=True)),
                ('cov_20k', models.FloatField(blank=True, null=True)),
                ('cov_30k', models.FloatField(blank=True, null=True)),
                ('cov_40k', models.FloatField(blank=True, null=True)),
                ('cov_50k', models.FloatField(blank=True, null=True)),
                ('cov_60k', models.FloatField(blank=True, null=True)),
                ('cov_80k', models.FloatField(blank=True, null=True)),
                ('cov_100k', models.FloatField(blank=True, null=True)),
                ('cov_150k', models.FloatField(blank=True, null=True)),
                ('cov_200k', models.FloatField(blank=True, null=True)),
                ('cov_250k', models.FloatField(blank=True, null=True)),
                ('cov_300k', models.FloatField(blank=True, null=True)),
                ('plan_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'tugoplan_med',
            },
        ),
        migrations.CreateModel(
            name='TugoplanNomed',
            fields=[
                ('age_from', models.PositiveIntegerField()),
                ('age_to', models.PositiveIntegerField()),
                ('cov_10k', models.FloatField(blank=True, null=True)),
                ('cov_20k', models.FloatField(blank=True, null=True)),
                ('cov_30k', models.FloatField(blank=True, null=True)),
                ('cov_40k', models.FloatField(blank=True, null=True)),
                ('cov_50k', models.FloatField(blank=True, null=True)),
                ('cov_60k', models.FloatField(blank=True, null=True)),
                ('cov_80k', models.FloatField(blank=True, null=True)),
                ('cov_100k', models.FloatField(blank=True, null=True)),
                ('cov_150k', models.FloatField(blank=True, null=True)),
                ('cov_200k', models.FloatField(blank=True, null=True)),
                ('cov_250k', models.FloatField(blank=True, null=True)),
                ('cov_300k', models.FloatField(blank=True, null=True)),
                ('plan_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'tugoplan_nomed',
            },
        ),
    ]
