# Generated by Django 2.1 on 2018-09-09 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insprices', '0002_gmsplanmed_tfirstplan_med_tfirstplan_nomed_tugoplanmed_tugoplannomed'),
    ]

    operations = [
        migrations.CreateModel(
            name='GMSplanNomed',
            fields=[
                ('age_from', models.PositiveIntegerField()),
                ('age_to', models.PositiveIntegerField()),
                ('cov_25k', models.FloatField(blank=True, null=True)),
                ('cov_50k', models.FloatField(blank=True, null=True)),
                ('cov_100k', models.FloatField(blank=True, null=True)),
                ('cov_150k', models.FloatField(blank=True, null=True)),
                ('plan_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'gmsplan_nomed',
            },
        ),
        migrations.RenameModel(
            old_name='Tfirstplan_nomed',
            new_name='TfirstplanMed',
        ),
        migrations.RenameModel(
            old_name='Tfirstplan_med',
            new_name='TfirstplanNomed',
        ),
        migrations.AlterModelTable(
            name='tfirstplanmed',
            table='tfirstplan_med',
        ),
        migrations.AlterModelTable(
            name='tfirstplannomed',
            table='tfirstplan_nomed',
        ),
    ]
